services:
  app:
    build:
      context: .
      ssh:
        - default
    command: ["server"]
    env_file:
      - path: ./.env
        required: false
    environment:
      PINECONE_MODE: cloud
      PINECONE_CONTROLLER_HOST: ""
    ports:
      - "8787:8787"
    volumes:
      - ./config.cloud.yaml:/app/deployments/example/config.yaml:ro
      - ./data:/app/data

  reindex:
    build:
      context: .
      ssh:
        - default
    profiles: ["reindex"]
    command: ["reindex"]
    env_file:
      - path: ./.env
        required: false
    environment:
      PINECONE_MODE: cloud
      PINECONE_CONTROLLER_HOST: ""
    volumes:
      - ./config.cloud.yaml:/app/deployments/example/config.yaml:ro
      - ./data:/app/data
